Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/trusty64"

  host_folder = "./files"

  config.vm.define "frontend" do |frontend|
    frontend.vm.hostname = "frontend"
    frontend.vm.network "private_network", ip: "192.168.28.2"
    frontend.vm.provider "virtualbox" do |vb|
      vb.name = "frontend"
      vb.cpus = 1
      vb.memory = 512
    end

    frontend.vm.synced_folder host_folder, "/home/vagrant/files", type: "virtualbox"

  end

  config.vm.define "backend" do |backend|
    backend.vm.hostname = "backend"
    backend.vm.network "private_network", ip: "192.168.28.3"
    backend.vm.provider "virtualbox" do |vb|
      vb.name = "backend"
      vb.cpus = 1
      vb.memory = 1024
    end
  end

  config.vm.define "db" do |db|
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.56.4"
    db.vm.provider "virtualbox" do |vb|
      vb.name = "db"
      vb.cpus = 1
      vb.memory = 2048
    end
  end

end
